site_name: C++ Notebook
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - cpp
nav:
  - 'Hello World': 'index.md'
  - 'Variables': 'variables.md'
  - 'Conditionals & Branching': 'conditionals.md'
  - 'Functions': 'functions.md'
  - 'Loops': 'loops.md'
  - 'Type Inference: 'type_inference.md'
  - 'Fundamental Types':
    - 'Primitives': 'fundamental_types/primitives.md'
    - 'Arrays': 'fundamental_types/arrays.md'
    - 'Structs': 'fundamental_types/structs.md'
  - 'Reference Types':
    - 'Pointers': 'reference_types/pointers.md'
    - 'References': 'reference_types/references.md'
    - 'Classes': 'reference_types/classes.md'
markdown_extensions:
  - admonition