site_name: C++ Notebook
theme: readthedocs
nav:
  - 'Hello World': 'index.md'
  - 'Types & Variables': 'types-n-variables.md'
  - 'Conditionals & Branching': 'conditionals.md'
  - 'Functions': 'functions.md'
  - 'Arrays': 'arrays.md'
  - 'Loops': 'loops.md'
markdown_extensions:
  - admonition